name: siberian_husky_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^0.1.9
  flutter_launcher_icons: ^0.7.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/


flutter_native_splash:
  image: "assets/icon/icon.png"
  color: "0xFF64B5F6"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

